### ISSUE TITLE
questions when we run the code

### ISSUE THREAD

**Issue by peterwilson3912** [ouc-ocean-group/LDPS#1]
![image](https://user-images.githubusercontent.com/36145675/79147626-3a000b00-7d92-11ea-8839-06193c2d4199.png)

**Comment by GeoffreyChen777** [comment]
mkdir log

**Comment by peterwilson3912** [comment]
Thanks a lot! The result looks like this:
![image](https://user-images.githubusercontent.com/36145675/79243031-1517a080-7e43-11ea-9f79-e714405d82a8.png)

May I ask is this right? I'm not familiar with this project. Would you please explain more about this repo files? Thank you so much for your amazing work!

**Comment by GeoffreyChen777** [comment]
> Thanks a lot! The result looks like this:
> ![image](https://user-images.githubusercontent.com/36145675/79243031-1517a080-7e43-11ea-9f79-e714405d82a8.png)
> 
> May I ask is this right? I'm not familiar with this project. Would you please explain more about this repo files? Thank you so much for your amazing work!

Your output is correct.

You can read the paper to find more details about this project.
